'''
Problem 12
The sequence of triangle numbers is generated by adding the natural numbers.
    So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28.

The first ten terms would be:

    1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

Let us list the factors of the first seven triangle numbers:

 1: 1
 3: 1,3
 6: 1,2,3,6
10: 1,2,5,10
15: 1,3,5,15
21: 1,3,7,214
28: 1,2,4,7,14,28
We can see that 28 is the first triangle number to have over five divisors.

What is the value of the first triangle number to have over five hundred
    divisors?
----------------------------------------------------------------------
notes:
        need method to get all divisors:
        loop through 1 to target number
        record divisors and keep a record of the pair number
        if the number you are testing is greater than the largest of the
            pair numbers from divisors then you have found the whole set
----------------------------------------------------------------------
output:
Answer: 76576500
Most factors: 12375 with 576
[Finished in 9.3s]
----------------------------------------------------------------------
message:

You are the 133421st person to have solved this problem.
'''
import math


def triangleNumber(num):
    return sum([x for x in range(1, num+1, 1)])


def getFactors(num):
    out = set([1, num])

    interval = 2
    if num % 2 == 0:
        interval = 1
        out.add(2)
        out.add(num/2)

    testMax = int(math.sqrt(num)) + 1
    for i in range(3, testMax, interval):
        if num % i == 0:
            out.add(i)
            out.add(num/i)

    return out


def main():
    top = 0
    topNum = None
    for num in range(1, 100000, 1):
        triangle = triangleNumber(num)
        factors = getFactors(triangle)
        count = len(factors)
        print(str(num) + ": " +
              str(triangle) +
              " - factors (" +
              str(count) + "): " +
              str(factors))

        if count > top:
            top = count
            topNum = num
        if count > 500:
            print("Answer: " + str(triangle))
            break

    print("Most factors: " + str(topNum) + " with " + str(top))

if __name__ == '__main__':
    main()
