'''
Each new term in the Fibonacci sequence is generated by adding the previous two
terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed
four million, find the sum of the even-valued terms.

-------------------------------------------------

You are the 422386th person to have solved this problem.

Complete - total = 4613732
[Finished in 0.1s]
'''

total = 0

fib0 = 1
fib1 = 2

while fib1 < 4000000:
    if fib1 % 2 == 0:
        total = total + fib1

    temp = fib1
    fib1 = temp + fib0
    fib0 = temp

    print("Running - fib1 = " + str(fib1))

print("Complete - total = " + str(total))
